# a build with no CI
trigger: none

variables:
  BuildConfiguration: ServicesCoreEventGrid
  BuildPlatform: Any CPU
  BuildType: App
  ConnectedServiceName_local: $(ConnectedServiceName)

jobs:
- job: NetCore_EventGrid_Function_Build_and_Deploy
  pool:
    name: Hosted VS2017
    demands: 
    - msbuild
    - visualstudio
    - vstest
  steps:
  - template: ./build.yaml
    parameters:
      ConnectedServiceName: $(ConnectedServiceName_local)