variables:
  BuildConfiguration: ServiceCoreServiceBus
  BuildPlatform: Any CPU

jobs:
- job: NetCore_ServiceBus_Function_Build_and_Deploy
  pool:
    name: Hosted VS2017
    demands: 
    - msbuild
    - visualstudio
    - vstest
  steps:
  - template: ./build.yaml