# a build with no CI
trigger: none

variables:
  BuildConfiguration: WebCore
  BuildPlatform: Any CPU

jobs:
- job: NetCore_Web_Build_and_Deploy
  pool:
    name: Hosted VS2017
    demands: 
    - msbuild
    - visualstudio
    - vstest
  steps:
  - template: ./build.yaml
    parameters:
      ConnectedServiceName: $(ConnectedServiceName)