variables:
  BuildConfiguration: WebFull
  BuildPlatform: Any CPU

jobs:
- job: NetFramework_Web_Build_and_Deploy
  pool:
    name: Hosted VS2017
    demands: 
    - msbuild
    - visualstudio
    - vstest
  steps:
  - template: ./build.yaml
    parameters:
      ConnectedServiceName: $(ConnectedServiceName)